// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingPong.proto

package com.abhinav.demo.proto_gen.ping_pong;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string payload = 1;</code>
   */
  java.lang.String getPayload();
  /**
   * <code>string payload = 1;</code>
   */
  com.google.protobuf.ByteString
      getPayloadBytes();
}
