// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingPong.proto

package com.abhinav.demo.proto_gen.ping_pong;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
